lab-4/odlid/cart/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = "cart"


urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:product_id>/", views.cart_remove, name="cart_remove"),
]

lab-4/odlid/home/urls.py
from . import views
from django.urls import path

app_name = "home"

urlpatterns = [
    path("", views.index, name="home"),
    path("categories", views.category_list, name="categories"),
    path("create-category", views.create_category, name="create_category"),
    path("create-model", views.create_model, name="create_model"),
    path("about", views.about_us, name="about"),
    path("news", views.news, name="news"),
    path("contacts", views.contacts, name="contacts"),
    path("faq", views.faq, name="faq"),
    path("toys-list/create", views.create_product, name="create"),
    path("toys-list/delete/<int:id>", views.delete_product, name="delete"),
    path("toys-list/edit/<int:id>", views.edit_product, name="edit"),
    path("toys-list/detail/<int:id>", views.product_details, name="detail"),
    path("toys-list/<str:category>", views.toys_list, name="toys_list_by_category"),
    path("toys-list", views.toys_list, name="toys_list"),
]

lab-4/odlid/odlid/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView


urlpatterns = [
    path("", RedirectView.as_view(url="home/", permanent=False), name="index"),
    path("auth/", include("login.urls", namespace="login")),
    path("home/", include("home.urls", namespace="home")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("order/", include("order.urls", namespace="order")),
    path("admin/", admin.site.urls),
    path("account/", include("analyzer.urls", namespace="account")),
    path("verification/", include("verify_email.urls")),
]

lab-4/odlid/order/urls.py
from . import views
from django.urls import path

app_name = "order"

urlpatterns = [
    path("create/", views.order_create, name="order_create"),
]

lab-4/odlid/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 30)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

lab-4/odlid/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.core.exceptions import PermissionDenied
from .cart import Cart
from .forms import CartAddProductForm
from home.models import Product


@require_POST
def cart_add(request, product_id):
    if not request.user.is_authenticated:
        raise PermissionDenied("You must to sign in")

    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd["quantity"], update_quantity=cd["update"])
    return redirect("cart:cart_detail")


def cart_remove(request, product_id):
    if not request.user.is_authenticated:
        raise PermissionDenied("You must to sign in")

    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect("cart:cart_detail")


def cart_detail(request):
    if not request.user.is_authenticated:
        raise PermissionDenied("You must to sign in")
    cart = Cart(request)
    return render(request, "cart/details.html", {"cart": cart})

lab-4/odlid/cart/templates/cart/details.html
{% extends "base.html" %}
{% load static %}
{% block title %}
<title>Your cart</title>
{% endblock %}

{% block css%}
<link rel="stylesheet" href="{% static 'details.css' %}">
{% endblock %}



{% block content %}
<div class="container text-center">
    <div class="row align-items-start">
        <div class="col">
        </div>
        <div class="col">
            <table style="margin-top: 10px;" class="table table-dark table-hover">
                <thead>
                    <tr>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Cost</th>
                        <th>Quantity</th>
                        <th>Price</th>
                        <th>Remove</th>
                    </tr>
                </thead>

                <tbody>
                    {% for item in cart %}
                    {% with product=item.product %}
                    <tr>
                        <td>
                            <img style="max-width: 250px; max-height: 200px;object-fit: cover;" src="
                            {% if product.image %}
                                {{ product.image.url }}
                            {% else %}
                                {% static 'img/no_image.png' %}
                            {% endif %}">
                        </td>
                        <td>{{ product.name }}</td>
                        <td>{{ item.cost }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>{{ item.total_price }}</td>
                        <td><a href="{% url 'cart:cart_remove' product.id %}">Remove from cart</a></td>
                    </tr>
                    {% endwith %}
                    {% endfor %}
                    <tr class="total">
                        <td>Total</td>
                        <td colspan="4"></td>
                        <td class="num">{{ cart.get_total_price }}</td>
                    </tr>
                </tbody>
            </table>

            <form id="promoForm">
                <label>Promo: </label>
                <input id="input_promo" placeholder="Enter your promo">
                <button type="button" id="btnCheckPromo">Check Promo</button>
            </form>
            

            <div class="buttons">
                <a href="{% url 'home:toys_list' %}" type="button">Continue shopping</a>
                <a href="{% url 'order:order_create' %}" type="button">
                    Checkout
                </a>
            </div>
        </div>
        <div class="col">

        </div>
    </div>
</div>

<script src="{% static 'js/promo.js' %}"></script>

{% endblock %}