lab-4/odlid/analyzer/urls.py
from django.urls import path
from . import views


app_name = "account"

urlpatterns = [
    path("history", views.user_order_history, name="history"),
    path("analyze", views.shop_analyzer, name="analyze"),
    path("reviews", views.reviews_page, name="reviews"),
    path("create-review", views.create_review, name="create_review"),
    path('promo', views.promo, name='promo'),
    path('check_promo/<int:promo>', views.check_promo, name='check_promo'),
    path('test', views.test, name='test'),
    path('task', views.task, name='task')
]

lab-4/odlid/cart/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = "cart"


urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:product_id>/", views.cart_remove, name="cart_remove"),
]

lab-4/odlid/login/urls.py
from . import views
from django.urls import path

app_name = "login"

urlpatterns = [
    path("register/", views.RegistrationView.as_view(), name="registration"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
]

lab-4/odlid/odlid/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView


urlpatterns = [
    path("", RedirectView.as_view(url="home/", permanent=False), name="index"),
    path("auth/", include("login.urls", namespace="login")),
    path("home/", include("home.urls", namespace="home")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("order/", include("order.urls", namespace="order")),
    path("admin/", admin.site.urls),
    path("account/", include("analyzer.urls", namespace="account")),
    path("verification/", include("verify_email.urls")),
]

lab-4/odlid/analyzer/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from login.models import Client


class Review(models.Model):
    user = models.ForeignKey(Client, on_delete=models.CASCADE)
    date = models.DateTimeField("date", null=False)
    rating = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    description = models.TextField(null=False)


class PromoCode(models.Model):
    name = models.TextField(null=False)
    code = models.IntegerField()
    is_active = models.BooleanField(null=False, default=True)
    discount = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(100)])

lab-4/odlid/analyzer/views.py
import json
from django.shortcuts import render
from django.core import serializers
from django.core.exceptions import PermissionDenied
from order.models import Order, OrderItem
from analyzer.models import Review, PromoCode
from home.models import Product
from datetime import datetime, timezone
from django.http import HttpResponseNotFound, HttpResponseRedirect, JsonResponse
from io import BytesIO
import base64
import matplotlib.pyplot as plt


def user_order_history(request):
    if not request.user.is_authenticated:
        raise PermissionDenied("You must be authorized")

    orders = Order.objects.filter(client_id=request.user.id)
    order_items = dict()
    for o in orders:
        order_items[o.id] = OrderItem.objects.filter(order_id=o.id)

    return render(
        request, "history.html", {"orders": orders, "order_items": order_items}
    )


def get_plot():
    x = [o.created for o in Order.objects.all()]
    y = []
    for el in x:
        orders_in_date = Order.objects.all().filter(created=el)
        for order in orders_in_date:
            quantity = sum([i.quantity for i in order.items.all()])
        y.append(quantity)

    plt.plot(x, y)
    buf = BytesIO()
    plt.savefig(buf, format="png")
    buf.seek(0)
    string = base64.b64encode(buf.read())
    return string.decode("utf-8")


def shop_analyzer(request):
    if not request.user.is_staff:
        raise PermissionDenied("Your role is too weak")

    purchase_count = Product.objects.values_list("cost", "purchase_count")

    total_income = 0
    total_count = 0

    for el in purchase_count:
        total_income += el[0] * el[1]
        total_count += el[1]

    most_valuable_product = Product.objects.order_by("purchase_count").first()
    min_valuable_product = Product.objects.order_by("-purchase_count").first()
    plot = get_plot()
    return render(
        request,
        "analyze.html",
        {
            "total_income": total_income,
            "total_count": total_count,
            "most_valuable_product": most_valuable_product,
            "min_valuable_product": min_valuable_product,
            "plot": plot,
        },
    )


def reviews_page(request):
    reviews = Review.objects.all()
    return render(request, "reviews.html", {"reviews": reviews})


def create_review(request):
    if request.method == "POST":
        review = Review(
            user=request.user,
            date=datetime.now(tz=timezone.utc).isoformat(timespec="seconds"),
            rating=request.POST.get("rating"),
            description=request.POST.get("description"),
        )
        review.save()
    else:
        return render(request, "create_review.html")

    return HttpResponseRedirect("/account/reviews")


def promo(request):
    promo_codes = PromoCode.objects.all()
    return render(request, "promo.html", {"promocodes": promo_codes})


def check_promo(request, promo):
    promo = PromoCode.objects.filter(code=promo).first()
    if promo is not None and promo.is_active:
        return JsonResponse(data={"valid": True, "discount": promo.discount})
    else:
        return HttpResponseNotFound()


def test(request):
    return render(request, "test.html")


def task(request):
    return render(request, "task.html")

lab-4/odlid/analyzer/templates/analyze.html
{% extends "base.html" %}
{% load static %}


{% block title %}
<title>Analyzer</title>
{% endblock %}


{% block css%}
<link rel="stylesheet" href="{% static 'details.css' %}">
{% endblock %}


{% block content %}
<div class="product-detail">
    <h1>Total income form toys: {{ total_income }}</h1>
    <h1>Total count are sold: {{ total_count }}</h1>
    <h1>Most valuable toy:
        <a href="{{ most_valuable_product.get_detail_url }}">
            {{ most_valuable_product.name }}</a>
    </h1>
    <h1>Least valuable toy:
        <a href="{{ most_valuable_product.get_detail_url }}">
            {{ min_valuable_product.name }}</a>
    </h1>

    <img src="data:image/png;base64, {{ plot }}">
</div>

{% endblock %}

lab-4/odlid/analyzer/templates/create_review.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Create review</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'create_review.css' %}">

{%endblock%}

{% block content %}

<div class="container">
    <div class="py-5 text-center">
        <h2>Review form</h2>
        <p class="lead">When leaving a review, please be as honest as possible. Avoid leaving angry or
            negative reviews before contacting us. Let's be a friendly community :)</p>
    </div>

    <form class="review-form" method="post" novalidate="">
        <h4 class="mb-3">Review</h4>
        {% csrf_token %}
        <div class="form-group">
            <label for="review-description" class="form-label">Description</label>
            <textarea class="form-control" id="review-description" name="review-description" placeholder="Leave your comment here"
                value="" required=""></textarea>
            <span class="input-warning">
                Valid description is required.
            </span>

            <div class="form-group">
                <label for="rating" class="form-label">Rating</label>
                <select class="form-select" name="rating" id="rating" required="">
                    <option value="">Choose...</option>
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                </select>
                <span class="input-warning">
                    Please select a valid rating.
                </span>
            </div>

            <button type="submit" id="submit-button" disabled>Create review</button>
    </form>
</div>


<script type="text/javascript" src="{% static 'js/review_button.js' %}"></script>


{% endblock %}

lab-4/odlid/analyzer/templates/history.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Order history</title>
{% endblock %}


{% block css%}
<link rel="stylesheet" href="{% static 'details.css' %}">
{% endblock %}



{% block content %}
<div class="container text-center">
    <div class="row align-items-start">
        <div class="col">
        </div>
        <div class="col">
            <table style="margin-top: 10px;" class="table table-dark table-hover">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in orders %}
                    <tr>
                        <td>{{ order.created }}</td>
                        <td>{{ order.get_total_cost }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <input class="GoBackButton" type="button" value="Go back to catalog" onclick="history.back()">

        </div>
        <div class="col">
        </div>
    
    </div>
</div>

{% endblock %}

lab-4/odlid/analyzer/templates/promo.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'promo.css' %}">
{%endblock%}


{% block content %}

<h1 class="h1">Promocodes and sales</h1>

<h2 class="h2">Active</h2>
<ul class="promo-list">
    {% for promo in promocodes %}
    {%  if promo.is_active %}
    <li class="promo-list-item">
        <span class="promo-list-item-title">{{ promo.name }}</span>
        <span class="promo-list-item-discount">{{ promo.discount }}%</span>
    </li>
    {% endif %}
    {% endfor %}
</ul>


<h2 class="h2">Archived</h2>
<ul class="promo-list">
    {% for promo in promocodes %}
    {%  if not promo.is_active %}
    <li class="promo-list-item">
        <span class="promo-list-item-title">{{ promo.name }}</span>
        <span class="promo-list-item-discount">{{ promo.discount }}%</span>
    </li>
    {% endif %}
    {% endfor %}
</ul>


{% endblock %}

lab-4/odlid/analyzer/templates/reviews.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Reviews</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'review.css' %}">
{% endblock %}

{% block content %}
<div class="d-grid gap-2 col-6 mx-auto py-5">
    <a href="{% if user.is_authenticated %} {% url 'account:create_review' %} {% else %} {% url 'login:login' %} {% endif %}"
        class="btn btn-primary btn-lg">Create review</a>
</div>

<div class="list-group list-group-numbered gap-2 mx-auto py-3 px-5">
    {% for r in reviews %}
    <div class="list-group-item d-flex justify-content-between align-items-start">
        <div class="ms-2 me-auto">
            <div class="fw-bold">{{ r.user.username }}</div>
            <div class="fw-bold">{{ r.date }}</div>
            <q>{{ r.description }}</q>
        </div>
        <span class="badge bg-primary rounded-pill">{{ r.rating }}/5</span>
    </div>
    {% endfor %}
</div>




{% endblock %}

lab-4/odlid/analyzer/templates/task.html
{% extends "base.html" %}
{% load static %}


{% block title %}
<title>Task</title>
{% endblock %}

{% block css %}

{% endblock %}


{% block content %}

<form id="dateForm">
    <label for="month">Месяц:</label>
    <input type="text" id="month" placeholder="Месяц">
    <label for="day">Число:</label>
    <input type="number" id="day" min="1" max="31" placeholder="Число">
    <label for="file">Импорт из файла:</label>
    <input type="file" id="file" accept=".txt">
    <button type="submit">Добавить</button>
</form>

<div>
    <h3>Летние даты (summer):</h3>
    <ul id="summerDates"></ul>
</div>

<div>
    <h3>Зимние даты (winter):</h3>
    <ul id="winterDates"></ul>
</div>

<script src="{% static 'js/tasks/task.js' %}"></script>

{% endblock %}

lab-4/odlid/analyzer/templates/test.html
{% extends "base.html" %}
{% load static %}


{% block title %}
<title>Test</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'table.css' %}">
{% endblock %}


{% block content %}

<div id="table-controls">
    <label for="table-size">Размер таблицы: </label>
    <input type="number" id="table-size" min="1">
    <button id="create-table-button">Создать таблицу</button>
  </div>    
<div id="table-container">
    <button id="transpose-button">Транспонировать</button>
    <button id="add-row-button">Добавить ряд</button>
    <button id="add-column-button">Добавить колонку</button>
    <label for="max-selection">Макс. выбор ячеек в ряду/колонке: </label>
    <input type="number" id="max-selection" min="1">
    <table id="table"></table>
  </div>

  <script type="text/javascript" src="{% static 'js/table.js' %}"></script>

{% endblock %}
  