lab-4/odlid/analyzer/urls.py
from django.urls import path
from . import views


app_name = "account"

urlpatterns = [
    path("history", views.user_order_history, name="history"),
    path("analyze", views.shop_analyzer, name="analyze"),
    path("reviews", views.reviews_page, name="reviews"),
    path("create-review", views.create_review, name="create_review"),
    path('promo', views.promo, name='promo'),
    path('check_promo/<int:promo>', views.check_promo, name='check_promo'),
    path('test', views.test, name='test'),
    path('task', views.task, name='task')
]

lab-4/odlid/cart/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = "cart"


urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:product_id>/", views.cart_remove, name="cart_remove"),
]

lab-4/odlid/home/urls.py
from . import views
from django.urls import path

app_name = "home"

urlpatterns = [
    path("", views.index, name="home"),
    path("categories", views.category_list, name="categories"),
    path("create-category", views.create_category, name="create_category"),
    path("create-model", views.create_model, name="create_model"),
    path("about", views.about_us, name="about"),
    path("news", views.news, name="news"),
    path("contacts", views.contacts, name="contacts"),
    path("faq", views.faq, name="faq"),
    path("toys-list/create", views.create_product, name="create"),
    path("toys-list/delete/<int:id>", views.delete_product, name="delete"),
    path("toys-list/edit/<int:id>", views.edit_product, name="edit"),
    path("toys-list/detail/<int:id>", views.product_details, name="detail"),
    path("toys-list/<str:category>", views.toys_list, name="toys_list_by_category"),
    path("toys-list", views.toys_list, name="toys_list"),
]

lab-4/odlid/login/urls.py
from . import views
from django.urls import path

app_name = "login"

urlpatterns = [
    path("register/", views.RegistrationView.as_view(), name="registration"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
]

lab-4/odlid/odlid/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView


urlpatterns = [
    path("", RedirectView.as_view(url="home/", permanent=False), name="index"),
    path("auth/", include("login.urls", namespace="login")),
    path("home/", include("home.urls", namespace="home")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("order/", include("order.urls", namespace="order")),
    path("admin/", admin.site.urls),
    path("account/", include("analyzer.urls", namespace="account")),
    path("verification/", include("verify_email.urls")),
]

lab-4/odlid/home/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
import datetime
from django.urls import reverse
from decimal import Decimal


class ProductCategory(models.Model):
    name = models.CharField(max_length=200, help_text="Enter category name")

    image = models.ImageField(upload_to="static/images", blank=True, null=True)

    def get_url(self):
        return reverse("home:toys_list_by_category", args=[str(self.id)])

    def __str__(self) -> str:
        return self.name.__str__()


class ProductModel(models.Model):
    name = models.CharField(max_length=200, help_text="Enter model name")

    def year_choices(self):
        return [(r, r) for r in range(1999, datetime.date.today().year + 1)]

    def current_year(self):
        return datetime.date.today().year

    def max_value_current_year(self, value):
        return MaxValueValidator(self.current_year())(value)

    year_of_manufacture = models.IntegerField(
        validators=[MinValueValidator(1984), max_value_current_year]
    )

    def __str__(self) -> str:
        return self.name.__str__()


class Product(models.Model):
    name = models.CharField(max_length=200, help_text="Enter product name")

    code = models.PositiveIntegerField(help_text="Enter product code")

    image = models.ImageField(upload_to="static/images", blank=True, null=True)

    model = models.ForeignKey(
        ProductModel, on_delete=models.CASCADE, blank=True, null=True
    )
    cost = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        help_text="Enter product cost",
        validators=[MinValueValidator(Decimal("0.01"))],
    )

    in_prod = models.BooleanField(help_text="Enter is product in production")

    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, null=True)

    purchase_count = models.PositiveIntegerField(default=0)

    def get_detail_url(self):
        return reverse("home:detail", args=[str(self.id)])

    def get_edit_url(self):
        return reverse("home:edit", args=[str(self.id)])

    def get_delete_url(self):
        return reverse("home:delete", args=[str(self.id)])


class News(models.Model):
    image_url = models.CharField(null=False)
    name = models.CharField(null=False)
    description = models.CharField(null=False)
    continue_url = models.CharField(null=False, default="localhost:8080")

lab-4/odlid/home/forms.py
from django import forms
from .models import Product, ProductModel, ProductCategory


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["name", "code", "model", "image", "cost", "in_prod", "category"]


class ProductCategoryForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = ["name", "image"]


class ProductModelForm(forms.ModelForm):
    class Meta:
        model = ProductModel
        fields = ["name", "year_of_manufacture"]

lab-4/odlid/home/views.py
from django.shortcuts import render, get_object_or_404
from .models import ProductCategory, Product, ProductModel, News
from django.core.exceptions import PermissionDenied
from .forms import ProductForm, ProductCategoryForm, ProductModelForm
from django.http import HttpResponseRedirect, HttpResponseNotFound
from cart.forms import CartAddProductForm


def index(request):
    product = Product.objects.all()
    return render(request, "index.html", {"latest_products": product[::-1][0:3]})


def category_list(request, category=None):
    categories = ProductCategory.objects.all()

    return render(request, "categories.html", {"categories": categories})


def toys_list(request, category=None):
    categories = ProductCategory.objects.all()
    print(category)
    if category:
        category = ProductCategory.objects.get(id=category)
        toys = Product.objects.filter(category=category)
    else:
        toys = Product.objects.all()

    sort = request.GET.get("sort")

    if str(sort) == "ascending":
        toys = toys.order_by("cost")
    elif str(sort) == "descending":
        toys = toys.order_by("-cost")
    return render(
        request,
        "toys.html",
        {
            "toys": toys,
            "categories": categories,
            "request": request,
            "category": category,
        },
    )


def product_details(request, id):
    product = get_object_or_404(Product, id=id)
    cart_product_form = CartAddProductForm()

    return render(
        request,
        "details.html",
        {"product": product, "cart_product_form": cart_product_form},
    )


def create_product(request):
    if not request.user.is_staff:
        raise PermissionDenied("Your role is to weak")

    form = ProductForm()

    if request.method == "POST":
        product = Product.objects.create(
            name=request.POST.get("name"),
            code=request.POST.get("code"),
            image=request.FILES.get("image"),
            model=ProductModel.objects.get(id=request.POST.get("model")),
            cost=request.POST.get("cost"),
            in_prod=request.POST.get("in_prod") == "on",
            category=ProductCategory.objects.get(id=request.POST.get("category")),
        )
        product.save()
    else:
        return render(request, "create.html", {"form": form, "is_product": True})
    return HttpResponseRedirect("/home/categories")


def edit_product(request, id):
    if not request.user.is_staff:
        raise PermissionDenied("Your role is to weak")

    try:
        product = Product.objects.get(id=id)

        form = ProductForm(
            initial={
                "name": product.name,
                "code": product.code,
                "model": product.model,
                "image": product.image,
                "cost": product.cost,
                "in_prod": product.in_prod,
                "category": product.category,
            }
        )
        print(request.FILES.get("image"))
        if request.method == "POST":
            product.name = request.POST.get("name")
            product.code = request.POST.get("code")
            product.model = ProductModel.objects.get(id=request.POST.get("model"))
            product.cost = request.POST.get("cost")
            product.image = request.FILES.get("image")
            product.in_prod = request.POST.get("in_prod") == "on"
            product.category = ProductCategory.objects.get(
                id=request.POST.get("category")
            )

            product.save()

            return HttpResponseRedirect("/home/toys-list")
        else:
            return render(
                request,
                "edit.html",
                {"product": product, "form": form, "is_product": True},
            )
    except Exception:
        return HttpResponseNotFound("<h2>Product is not found</h2>")


def delete_product(request, id):
    if not request.user.is_staff:
        raise PermissionDenied("Your role is to weak")

    try:
        product = Product.objects.get(id=id)
        product.delete()
        return HttpResponseRedirect("/home/toys-list")
    except Exception:
        return HttpResponseNotFound("<h1>Product not found</h1>")


def create_category(request):
    if not request.user.is_staff:
        raise PermissionDenied("Your role is to weak")

    form = ProductCategoryForm()

    if request.method == "POST":
        product_category = ProductCategory.objects.create(
            name=request.POST.get("name"), image=request.FILES.get("image")
        )
        product_category.save()
    else:
        return render(request, "create.html", {"form": form})
    return HttpResponseRedirect("/home/categories")


def create_model(request):
    if not request.user.is_staff:
        raise PermissionDenied("Your role is to weak")

    form = ProductModelForm()

    if request.method == "POST":
        product_model = ProductModel.objects.create(
            name=request.POST.get("name"),
            year_of_manufacture=request.POST.get("year_of_manufacture"),
        )
        product_model.save()
    else:
        return render(request, "create.html", {"form": form})
    return HttpResponseRedirect("/home/categories")


def news(request):
    return render(request, "news.html", {"news": News.objects.all()})


def contacts(request):
    return render(request, "contacts.html")


def about_us(request):
    return render(request, "about.html")


def faq(request):
    return render(request, "faq.html")
    

lab-4/odlid/home/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta itemprop="datePublished" datetime="2023-09-01">
    <link rel="icon" type="image/x-icon" href="{% static '/images/toys.png'%}">
    {% block title%}

    {% endblock %}

    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js"
        integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js"
        integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ"
        crossorigin="anonymous"></script> -->
    <link rel="stylesheet" href="{% static 'navbar.css'%}">
    <link rel="stylesheet" href="{% static 'base.css' %}">
    {% if not user.is_authenticated %}
    <!-- <script src="{% static 'js/birthdate.js' %}"></script> -->
    {% endif %}


    {% block css %}

    {% endblock %}
</head>



<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="menu">
                <a class="company-name text-with-shadow" href="{% url 'home:home' %}" class="navbar-brand"
                    href="#">ODLID.BY</a>
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li>
                        <a aria-current="page" href="{% url 'home:home' %}">Home</a>
                    </li>
                    <li>
                        <a aria-current="page" href="{% url 'home:categories' %}">Catalog</a>
                    </li>
                    <li>
                        <a aria-current="page" href="{% url 'home:news' %}">News</a>
                    </li>
                    <li>
                        <a aria-current="page" href="{% url 'account:reviews' %}">Reviews</a>
                    </li>
                    <li>
                        <a aria-current="page" href="{% url 'home:about' %}">About us</a>
                    </li>
                    <li>
                        <a aria-current="page" href="{% url 'home:contacts' %}">Contacts</a>
                    </li>
                    <li>
                        <a aria-current="page" href="{% url 'account:promo' %}">Promo</a>
                    </li>
                    <li>
                        <a aria-current="page" href="{% url 'home:faq' %}">FAQ</a>
                    </li>
                    <li>
                        <a aria-current="page" href="{% url 'account:test' %}">TEST</a>
                    </li>
                    <li>
                        <a aria-current="page" href="{% url 'account:task' %}">TASK</a>
                    </li>
                </ul>
            </div>

            {% if user.is_authenticated %}
            <div id="timer"></div>
            <script src="{% static 'js/timer.js' %}"></script>
            {% else %}
            <p id="current-time"></p>
            {% endif %}


            {% if user.is_authenticated %}
            <a href="{% url 'cart:cart_detail' %}" style="color:white;margin-right: 50px;">
                <img style="max-width: 25px; max-height: 25px;" src="{% static 'images/cart.png'%}">
                Your cart
                <img style="max-width: 25px; max-height: 25px;" src="{% static 'images/cart.png'%}">
            </a>

            <div class="dropdown">
                <a href="#" class="dropdown-toggle">Account &#9660;</a>
                <!-- <button class="dropbtn">Account &#9660;</button> -->
                <ul class="dropdown-menu">
                    <li><a href="{% url 'account:history' %}">History</a></li>
                    {% if user.is_staff%}
                    <li><a href="{% url 'account:analyze' %}">Analyze</a></li>
                    {% endif %}
                    <hr>
                    <li><a href="{% url 'login:logout' %}" onclick="clearLocalStorage()">Log out</a></li>
                </ul>
            </div>
            {% endif %}

            <form role="search">
                {% if not user.is_authenticated %}
                <div class="user-actions">
                    <a href="{% url 'login:login' %}" style="color:white; margin-right: 15px;">
                        LOG IN
                    </a>
                    <a href="{% url 'login:registration' %}" style="color:white;">
                        SIGN UP
                    </a>
                </div>
                {% endif %}
            </form>

        </nav>
    </header>

    <script>
        let time = document.getElementById('current-time');

        setInterval(() => {
            let d = new Date();
            time.innerHTML = "Current date: " + d.toLocaleDateString() + " " + d.toLocaleTimeString();
        }, 1000)

    </script>
    <main>
        {% block content %}

        {% endblock %}
    </main>

    <footer>
        <div>
            <span>© 2023 Company, Inc</span>
        </div>
        <a class="license visit" href="{% static 'LICENSE'%}" download>Privacy Policy</a>
    </footer>

</body>

</html>

lab-4/odlid/home/templates/categories.html
{% extends 'base.html'%}
{% load static %}

{% block css%}
<link rel="stylesheet" href="{% static 'categories.css'%}">
{%endblock%}

{% block title%}
<title>
    Home
</title>
{% endblock %}

{% block content %}

{% if user.is_staff %}
<div class="create-button">
    <a type="button" href="{% url 'home:create_category' %}" class="btn btn-primary">Create category</a>
</div>
{% endif %}


<div class="categories-list">

    <div class="item">
        <a href="{% url 'home:toys_list' %}">
            <img class="category_image" src="{% static 'images/all.png' %}">

            <div class="category-name">All</div>
        </a>
    </div>
    {% for category in categories %}

    <div class="item">
        <a href="{{ category.get_url }}">
            <img class="category_image"
                src="{% if category.image %} {{ category.image.url }} {% else %} {% static 'images/no_image.svg' %}{% endif %}">

            <div class="category-name">{{ category.name }}</div>
        </a>
    </div>
    {% endfor %}
</div>
{% endblock %}

lab-4/odlid/home/templates/contacts.html
{% extends 'base.html'%}
{% load static %}

{% block title%}
<title>
    Contacts
</title>
{% endblock %}

{% block content %}

{% block css %}
<link rel="stylesheet" href="{% static 'contacts.css' %}">
{%endblock%}


<h2 class="pb-2 border-bottom">Contacts</h2>

<div class="contacts-container">
    <div class="contact">
        <img src="{% static 'images/krosh.png'%}">
        <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">KROSH</h3>
        <p>Main toy supplier</p>
        <p>krosh@gmail.com</p>
    </div>
    <div class="contact">
        <img src="{% static 'images/nusha.png'%}">
        <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">NUSHA</h3>
        <p class="lead">Head of sales department</p>
        <p>nusha@gmail.com</p>

    </div>

    <div class="contact">
        <img src="{%static 'images/pin.png'%}">
        <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">PIN</h3>
        <p class="lead">Electric</p>
        <p>pin229@gmail.com</p>
    </div>
</div>
</div>

<h2 class="h2">Vacancies</h2>
<div class="vacancy">

    <details>
        <summary class="accordion-button">Store Manager
            <pre>   </pre> <span class="badge bg-primary rounded-pill">200-500$</span>
        </summary>
        <br>
        Responsibilities: Oversee daily operations, manage staff, ensure smooth functioning of the store, handle
        inventory management
        and ordering, develop and implement sales strategies, provide excellent customer service.
        <br>
        <br>
        Requirements: Previous retail management experience, strong leadership and organizational skills, knowledge of
        the toy industry, exceptional communication and problem-solving abilities.
    </details>

    <details class="list-group-item list-group-item-action accordion-body">
        <summary class="accordion-button">Sales Associate
            <pre>   </pre> <span class="badge bg-primary rounded-pill">1200-1500$</span>
        </summary>
        <br>
        <br>
        Responsibilities: Assist customers in finding and purchasing toys, provide product information and
        recommendations, handle cash transactions, maintain store cleanliness and visual merchandising, restock shelves.
        <br>
        <br>
        Requirements: Friendly and approachable demeanor, excellent customer service skills, ability to work in a team,
        knowledge or interest in toys, good communication and sales skills.

    </details>

    <details class="list-group-item list-group-item-action accordion-body">
        <summary class="accordion-button">Toy Demonstrator
            <pre>   </pre> <span class="badge bg-primary rounded-pill">800-900$</span>
        </summary>
        <br>
        <br>
        Responsibilities: Demonstrate and showcase toys to customers, explain features and functionalities, engage with
        children and parents, create an interactive and fun environment, answer customer questions.
        <br>
        <br>
        Requirements: Enthusiasm for toys and children, ability to captivate and entertain an audience, excellent
        presentation and communication skills, ability to work flexible hours including weekends.

    </details>

</div>


{% endblock %}

lab-4/odlid/home/templates/create.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html>

{% block title%}
<title>
    Create product
</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'register.css' %}">
{% endblock %}

{% block content %}

<body>
    <div id="wrap">
        <div id="content" style="max-width: fit-content; margin-top: 10%;">

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input id="button_save" type="submit" value="Save">
                {% if is_product %}
                <a href="{% url 'home:create_model' %}" id="button_save" type="button">Create model</a>
                {%endif%}
            </form>
        </div>

    </div>
</body>
{% endblock %}



</html>

lab-4/odlid/home/templates/details.html
{% extends "base.html" %}
{% load static %}


{% block title%}
<title>
    Details
</title>
{% endblock %}

{% block css%}
<link rel="stylesheet" href="{% static 'details.css' %}">
{% endblock %}

{% block content %}

<div class="product-detail">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}
    {% static 'images/no_image.svg' %}{% endif %}">
    <h1>Product name: {{ product.name }}</h1>
    <h2>
        Category: <a href="{{ product.category.get_url }}">{{ product.category.name }}</a>
    </h2>
    <h3 class="cost">Cost: {{ product.cost }}$</h3>
    <p>In production: {% if product.in_prod %}Yes{% else %}No{%endif%}</p>
    
    {% if user.is_authenticated %}
    
    <form action="{% url 'cart:cart_add' product.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="Add to cart">
    </form>
    
    {% endif %}

    <div class="additional-buttons">
        <input class="GoBackButton" type="button" value="Go back to catalog" onclick="history.back()">
        {%if user.is_staff%}
        <form action="{{ product.get_edit_url }}">
            <input onclick="location.href = '{{ product.get_edit_url }}'" type="button" href="" value="Edit"></input>
        </form>

        <form action="{{ product.get_delete_url }}">
            <input type="button" onclick="location.href='{{ product.get_delete_url }}'" value="Remove"></input>
        </form>
        {%endif%}
    </div>

</div>
{% endblock %}

lab-4/odlid/home/templates/edit.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html>
{% block title%}
<title>
    Edit product
</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'register.css' %}">
{% endblock %}

{% block content %}

<body>
    <div id="wrap">
        <div id="content" style="max-width: fit-content; margin-top: 10%;">

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input id="button_save" type="submit" value="Save">

            </form>
        </div>

    </div>
</body>
{% endblock %}



</html>

lab-4/odlid/home/templates/index.html
{% extends 'base.html'%}
{% load static %}

{% block title%}
<title>ODLID</title>
{% endblock %}

{%block css %}
<link rel="stylesheet" href="{% static 'home.css' %}">
{% endblock %}

{% block content %}



<div id="myCarousel" class="carousel slide mb-6" data-bs-ride="carousel">
  <div class="carousel-items">
    <div class="carousel-item active">

      <img class="d-block" src="{% static 'images/banner1.jpeg'%}"
        style="object-fit: cover; height: 620px; width: 1850px;" alt="First slide">
      <div class="container">
        <div class="carousel-caption text-start text-black">
          <h1>Join us today</h1>
          <p>Create a free account to make easy and fast purchases now.</p>
          <p><a class="btn btn-lg btn-primary" href="{% url 'login:registration' %}">Sign up today</a></p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img class="d-block" src="{% static 'images/banner.jpg'%}"
        style="object-fit: cover; height: 620px; width: 1850px;" alt="Second slide">
      </img>

      <div class="container">
        <div class="carousel-caption text-black">
          <h1>The best toys store in the world</h1>
          <p>Huge catalog of toys, low prices and much more</p>
          <p><a class="btn btn-lg btn-primary" href="{% url 'home:categories' %}">Learn more</a></p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img class="d-block" src="{% static 'images/banner3.jpg'%}"
        style="object-fit: cover; height: 620px; width: 1850px;" alt="First slide">
      </svg>

      <div class="container">
        <div class="carousel-caption text-end text-black">
          <h1>Huge company trusted by many</h1>
          <p>Learn about us and our companions</p>
          <p><a class="btn btn-lg btn-primary" href="#companions">About us</a></p>
        </div>
      </div>
    </div>
  </div>
  <button class="carousel-control prev" type="button">
    Previous
  </button>
  <button class="carousel-control next" type="button">
    Next
  </button>
</div>

{% if user.is_superuser %}
<form id="interval-form">
  <label for="interval">Интервал прокручивания (в секундах):</label>
  <input type="number" id="interval" value="5">
  <button id="update-interval">Обновить интервал</button>
</form>
{% endif %}

<hr>
<h1 id="companions" class="text-center">WE ARE TRUSTED</h1>
<div class="partners-container">
  <ul class="partners">
    <li class="partner">
      <a class="nav-item nav-link" href="https://www.funtastik.by/" target="_blank">
        <img class="round animated-img" src="{%static 'images/funtastik.png'%}"></img>
      </a>
    </li>
    <li class="partner">
      <a class="nav-item nav-link" href="https://www.detmir.by/" target="_blank">
        <img class="round animated-img" src="{%static 'images/detmir.jpg'%}"></img>
      </a>
    </li>
    <li class="partner">
      <a class="nav-item nav-link" href="https://en.wikipedia.org/wiki/Toy_Story" target="_blank">
        <img class="round animated-img" src="{%static 'images/toystory.png'%}"></img>
      </a>
    </li>
  </ul>
</div>

<hr>


<div class="grid-container">
  {% for product in latest_products%}
  <div class="grid-item">
    <div class="item-content">
    <img src="{{ product.image.url }}">
    <p class="title">{{ product.name }}</p>
    <div class="d-flex justify-content-between align-items-center">
      <a class="btn btn-sm btn-outline-secondary" href="{{ product.get_detail_url }}">Learn more</a>
      <small class="price">{{ product.cost }}$</small>
    </div>
    </div>
  </div>
  {% endfor %}
</div>

<script type="text/javascript" src="{% static 'js/carousel.js' %}"></script>
<script type="text/javascript" src="{% static 'js/partners.js' %}"></script>
{% endblock %}

lab-4/odlid/home/templates/news.html
{% extends 'base.html'%}
{% load static %}

{% block title%}
<title>
    News
</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'news.css' %}">
{% endblock %}

{% block content %}

<script>
    function toggleContent(name) {
        var content = document.getElementById(name);
        content.querySelector('.article-content').classList.toggle('show');
    }
</script>

{% for n in news %}
<div id="{{ n.name }}" class="article">
    <img src="{{ n.image_url }}" class="bd-placeholder-img rounded-circle" width="140" height="140"
        aria-label="Some picture" preserveAspectRatio="xMidYMid slice" focusable="false">
    <rect width="100%" height="100%" fill="var(--bs-secondary-color)"></rect>
    </img>
    <h2 class="article-title">{{ n.name }}</h2>
    <p class="article-summary">{{ n.description}}</p>
    <p class="article-content">{{ n.description }}</p>
    <div class="read-more" onclick="toggleContent('{{ n.name }}')">Learn more</div>
</div>
{% endfor %}



{% endblock %}

lab-4/odlid/home/templates/toys.html
{% extends 'base.html'%}
{% load static %}


{% block css%}
<link rel="stylesheet" href="{% static 'toys.css' %}">
{% endblock %}

{% block title%}
<title>
    Catalog
</title>
{% endblock %}

{% block content %}

{% if user.is_staff %}
<div class="create-button">
    <a type="button" href="{% url 'home:create' %}" class="btn btn-primary">Create product</a>
</div>
{% endif %}

<section class="container text-center">
    <div class="row align-items-center">
        <div class="col">
            <div class="list-group" style="background-color: dimgrey;">
                <a class="list-group-item list-group-item-action" href="{% url 'home:toys_list' %}">
                    <div class="category-name">All</div>
                </a>
                {% for c in categories %}

                <a class="list-group-item list-group-item-action" href="{{ c.get_url }}">
                    <div class="category-name">{{ c.name }}</div>
                </a>
                {% endfor %}
            </div>
        </div>

        <div class="col">

            <h1>{% if category %}{{ category.name }}{% else %}All{% endif %}</h1>


            <form class="button-form" action="{{ request.get_full_path }}" method="get">
                <button type="submit" name="sort" value="ascending">Sort by price ascending</button>
                <button type="submit" name="sort" value="descending">Sort by price descending</button>
            </form>
            <table class="table table-success table-striped">
                <tr>
                    <th>Name</th>
                    <th>Code</th>
                    <th>Cost</th>
                    <th>In Production</th>
                </tr>

                {% for toy in toys %}
                <tr>
                    <div class="item">
                        <td><a href="{{ toy.get_detail_url }}">
                                <div class="toy-name">{{ toy.name }}</div>
                            </a></td>
                        <td>{{ toy.code }}</td>
                        <td>{{ toy.cost }}</td>
                        <td><img style="height: 15px;width: 15px;"
                                src="{% if toy.in_prod %}{% static 'images/accept.png'%}{% else %}{% static 'images/not_accept.png'%}{%endif%}">
                        </td>
                    </div>
                </tr>
                {% endfor %}
            </table>
    </form>
        </div>
    </div>
</section>

{% endblock %}